name: ChestShopDatabase
version: '${version}'
main: io.github.md5sha256.chestshopdatabase.ChestshopDatabasePlugin
api-version: '1.21.8'
authors: [ md5sha256 ]
dependencies:
  server:
    ChestShop:
      join-classpath: true
      load: BEFORE
      required: true

permissions:
  csdb.find:
    description: "Permission to run /csdb find"
    default: op